### ISSUE TITLE
Translation in french

### ISSUE THREAD

**Issue by xidoc** [knpuniversity/symfony4#11]
Hi !
I would like to translate in french Stellar Development with Symfony 4.
If I translate, it's possible to have the translation on the [website](https://symfonycasts.com/screencast/symfony) ?
[I've already started.](https://github.com/xidoc/knpuniversity-symfony4-fr/blob/ep1-micro-app-phpstorm-fr/knpu/ep1-stellar/micro-app-phpstorm.md)
Are there any suggestions?

**Comment by xidoc** [comment]
Sorry ! I didn't see that Victor had answered me.

**Comment by bocharsky-bw** [comment]
No problem! I even put the reference to the conversation here just for the history:
https://github.com/knpuniversity/symfony4/commit/c971131dd159f92afd9ef681659d271559be057a#commitcomment-32730788
