### ISSUE TITLE
Select from junction table

### ISSUE THREAD

**Issue by plutonio00** [knpuniversity/symfony4#31]
Hello, everybody! 
What should I do if I need to make select from junction table?

For example, I develop project and I need to make chats between users. I have two entities: `User` and `Chat`, and many-to-many relation between them (accordingly, I have three tables: `user, chat, chat_user`). I try to get all chats, which user is member, and to get all users from these chats.

I made the following SQL query:

```
SELECT *
FROM chat c
         INNER JOIN chat_user cu ON c.id = cu.chat_id
         INNER JOIN user u ON u.id = cu.user_id
WHERE c.id IN (SELECT chat_id
               FROM chat_user
               WHERE user_id = <idUser>);
```

But I don't know how to translate in DQL subquery `SELECT chat_id FROM chat_user WHERE user_id = <idUser>`, because a haven't additional entity for table chat_user.

And I tried to add entity ChatUser and get data in ChatRepository smt. like this:

```
 public function getChatsData($idUser)
    {
        $subQuery = $this->getEntityManager()
            ->getRepository(ChatUser::class)
            ->createQueryBuilder('chus')
            ->select('chus.chat')
            ->andWhere('chus.user = :idUser')
            ->setParameter('idUser', $idUser)
        ;

        $qb = $this->createQueryBuilder('c');

        return $qb
            ->innerJoin('c.chatUsers', 'cu')
            ->addSelect('cu')
            ->innerJoin('cu.user', 'u')
            ->addSelect('u')
            ->innerJoin('c.messages', 'm')
            ->addSelect('m')
            ->andWhere('u.id = :idUser')
            ->andWhere($qb->expr()->in(
                'c.id',
                $subQuery->getQuery()->getResult()
            ))
            ->setParameter('idUser', $idUser)
            ->getQuery()
            ->getResult()
            ;
    }
```

but it doesn't work. I get error [Semantical Error] line 0, col 12 near 'chat FROM App\Entity\ChatUser': Error: Invalid PathExpression. Must be a StateFieldPathExpression.

Have Doctrine standard tools for such tasks?

**Comment by bocharsky-bw** [comment]
Just for the reference: Duplicate of https://github.com/knpuniversity/doctrine-queries/issues/4
